language: cpp

compiler: gcc

before_script:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo add-apt-repository --yes ppa:gstreamer-developers/ppa
  - sudo apt-get update -qq
 - wget http://launchpadlibrarian.net/151433644/libglib2.0-0_2.38.0-1ubuntu1_amd64.deb
  - sudo dpkg -i libglib2.0-0_2.38.0-1ubuntu1_amd64.deb
  - wget http://launchpadlibrarian.net/151433647/libglib2.0-bin_2.38.0-1ubuntu1_amd64.deb
  - sudo dpkg -i libglib2.0-bin_2.38.0-1ubuntu1_amd64.deb
  - wget http://launchpadlibrarian.net/151433648/libglib2.0-dev_2.38.0-1ubuntu1_amd64.deb
  - sudo dpkg -i libglib2.0-dev_2.38.0-1ubuntu1_amd64.deb
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - sudo apt-get install -qq cmake
  - sudo apt-get install -qq mm-common
  - sudo apt-get install -qq libsigc++-2.0-dev
  - sudo apt-get install -qq libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
  - sudo apt-get install -qq libffi-dev
  - sudo apt-get install -qq libxml-parser-perl
  - GST_CREATOR_DIRECTORY=$(pwd)
  - sudo apt-get install -qq libgtest-dev
  - cd /usr/src/gtest
  - sudo cmake .
  - sudo make
  - sudo mv libg* /usr/lib/
  - cd $GST_CREATOR_DIRECTORY
  - git clone git://git.gnome.org/glibmm
  - cd glibmm
  - git checkout 2.38.0
  - ./autogen.sh
  - make
  - sudo make install
  - cd ..
  - git clone git://git.gnome.org/gstreamermm
  - cd gstreamermm
  - ./autogen.sh
  - make
  - sudo make install
script:

branches:
  only:
    - master
